menu:
    博客: /
    微博: http://weibo.com/
    github: https://github.com/Lwxiang

favicon: /favicon.png
logo: /favicon.png

# comment
# e.g disqus: seansun
disqus: 
duoshuo: 

# google-analytics:
ga: 
# baidu-analytics:
ba: 
