menu:
    Blog: /
    Archives: /archives/
    Weibo: http://weibo.com/u/2931620085
    Github: https://github.com/Lwxiang
    Rss: /atom.xml

favicon: /favicon.png
logo: /favicon.png

# comment
# e.g disqus: seansun
disqus: 
duoshuo: 

# google-analytics:
ga: 
# baidu-analytics:
ba: 
